"""Add staff.uid column

Revision ID: f73601e43b4e
Revises: 
Create Date: 2026-01-29 00:25:03.153205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f73601e43b4e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_qualifications_id'), table_name='qualifications')
   #--- op.drop_table('qualifications')
    op.drop_index(op.f('ix_staff_qualifications_id'), table_name='staff_qualifications')
    op.drop_table('staff_qualifications')
    op.drop_constraint(op.f('organisations_name_key'), 'organisations', type_='unique')
    op.add_column('staff', sa.Column('uid', sa.String(), nullable=True))
    op.add_column('staff', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.drop_constraint(op.f('staff_email_key'), 'staff', type_='unique')
    op.create_unique_constraint(None, 'staff', ['uid'])
    op.drop_constraint(op.f('staff_organisation_id_fkey'), 'staff', type_='foreignkey')
    op.drop_column('staff', 'organisation_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff', sa.Column('organisation_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('staff_organisation_id_fkey'), 'staff', 'organisations', ['organisation_id'], ['id'])
    op.drop_constraint(None, 'staff', type_='unique')
    op.create_unique_constraint(op.f('staff_email_key'), 'staff', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_column('staff', 'created_at')
    op.drop_column('staff', 'uid')
    op.create_unique_constraint(op.f('organisations_name_key'), 'organisations', ['name'], postgresql_nulls_not_distinct=False)
    op.create_table('staff_qualifications',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('staff_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('qualification_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('expiry_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['qualification_id'], ['qualifications.id'], name=op.f('staff_qualifications_qualification_id_fkey')),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], name=op.f('staff_qualifications_staff_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('staff_qualifications_pkey'))
    )
    op.create_index(op.f('ix_staff_qualifications_id'), 'staff_qualifications', ['id'], unique=False)
    op.create_table('qualifications',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('qualifications_pkey'))
    )
    op.create_index(op.f('ix_qualifications_id'), 'qualifications', ['id'], unique=False)
    # ### end Alembic commands ###
